resources:
- name: eloqdoc_src
  type: git
  check_every: 3m
  source:
    branch: main
    uri: git@github.com:eloqdata/eloqdoc.git
    private_key: ((git-key))

- name: eloq_logservice_src
  type: git
  source:
    branch: main
    uri: git@github.com:eloqdata/eloq_log_service.git
    private_key: ((git-key))

- name: raft_host_manager_src
  type: git
  source:
    branch: main
    uri: git@github.com:eloqdata/raft_host_manager.git
    private_key: ((git-key))

- name: py_tpcc_src
  type: git
  source:
    branch: production
    uri: git@github.com:eloqdata/py-tpcc.git
    private_key: ((git-key))

- name: eloq_ubuntu_2404
  type: registry-image
  source:
    repository: eloqdata/monograph-dev-ci-ubuntu2404

jobs:
- name: compile-test
  build_log_retention:
    builds: 500
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: eloqdoc_src
        trigger: true
      - get: eloq_logservice_src
      - get: raft_host_manager_src
      - get: py_tpcc_src
      - get: eloq_ubuntu_2404
  - task: compile-test-task
    image: eloq_ubuntu_2404
    file: eloqdoc_src/concourse/tasks/main.ent.yml
    vars:
      cass-host: ((cassandra-host))
    privileged: true
