jobs:
  - name: major
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqdoc_src
              params:
                submodules: all
            - get: eloq_logservice_src
              params:
                submodules: all
            - get: raft_host_manager_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "major"
          GIT_SSH_KEY: ((git-key))
        file: eloqdoc_src/concourse/tasks/tag.yml
  - name: minor
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqdoc_src
              params:
                submodules: all
            - get: eloq_logservice_src
              params:
                submodules: all
            - get: raft_host_manager_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "minor"
          GIT_SSH_KEY: ((git-key))
        file: eloqdoc_src/concourse/tasks/tag.yml
  - name: patch
    serial: true
    plan:
      - in_parallel:
          limit: 2
          steps:
            - get: eloqdoc_src
              params:
                submodules: all
            - get: eloq_logservice_src
              params:
                submodules: all
            - get: raft_host_manager_src
              params:
                submodules: all
            - get: base_image
      - task: new-tag
        image: base_image
        params:
          TAG_LEVEL: "patch"
          GIT_SSH_KEY: ((git-key))
        file: eloqdoc_src/concourse/tasks/tag.yml

resources:
  - name: base_image
    source:
      repository: eloqdata/eloq-dev-ci-ubuntu2404
    type: registry-image

  - name: eloqdoc_src
    source:
      branch: main
      private_key: ((git-key))
      uri: git@github.com:eloqdata/eloqdoc.git
    type: git
  - name: eloq_logservice_src
    type: git
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq_log_service.git
      private_key: ((git-key))
  - name: raft_host_manager_src
    type: git
    source:
      branch: main
      uri: git@github.com:eloqdata/raft_host_manager.git
      private_key: ((git-key))