platform: linux
image_resource:
  type: registry-image
inputs:
  - name: eloq_logservice_src
  - name: eloqdoc_pr
  - name: raft_host_manager_src
run:
  path: eloqdoc_pr/concourse/scripts/pr.ent.bash
  args: ["((cass-host))"]
